version: '3.8'

services:
  mysql-sakila:
    image: restsql/mysql-sakila
    platform: linux/amd64
    container_name: mysql-sakila
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sakila
      - MYSQL_DATABASE=sakila
      - MYSQL_USER=sakila
      - MYSQL_PASSWORD=sakila
    volumes:
      - mysql-sakila-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-sakila-data:
    driver: local
